//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Funerial
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cat
    {
        public int Id { get; set; }
        public Nullable<int> Age { get; set; }
        public string Name { get; set; }
        public string Okras { get; set; }
        public Nullable<int> Id_Poroda { get; set; }
    
        public virtual Poroda Poroda { get; set; }
    }
}
