//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Funerial
{
    using System;
    using System.Collections.Generic;
    
    public partial class Documents
    {
        public int Id { get; set; }
        public Nullable<int> Id_Spec { get; set; }
        public Nullable<int> Id_Abityrient { get; set; }
    
        public virtual Abityrient Abityrient { get; set; }
        public virtual Special Special { get; set; }
    }
}
