//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Funerial
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class maximEntities3 : DbContext
    {
        public maximEntities3()
            : base("name=maximEntities3")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Abityrient> Abityrient { get; set; }
        public DbSet<Documents> Documents { get; set; }
        public DbSet<Introductory> Introductory { get; set; }
        public DbSet<Otdel> Otdel { get; set; }
        public DbSet<Special> Special { get; set; }
        public DbSet<Svaz> Svaz { get; set; }
        public DbSet<Users> Users { get; set; }
    }
}
