//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Funerial
{
    using System;
    using System.Collections.Generic;
    
    public partial class Otdel
    {
        public Otdel()
        {
            this.Special = new HashSet<Special>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Information { get; set; }
    
        public virtual ICollection<Special> Special { get; set; }
    }
}
