//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Funerial
{
    using System;
    using System.Collections.Generic;
    
    public partial class Special
    {
        public Special()
        {
            this.Documents = new HashSet<Documents>();
            this.Svaz = new HashSet<Svaz>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Prohod_Bal { get; set; }
        public Nullable<int> Id_Otdel { get; set; }
    
        public virtual ICollection<Documents> Documents { get; set; }
        public virtual Otdel Otdel { get; set; }
        public virtual ICollection<Svaz> Svaz { get; set; }
    }
}
